name: multimodal-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - tesseract>=4.1.1
  - pillow>=10.1.0
  - pandas>=2.1.4
  - pip:
    - langchain>=0.1.0
    - langchain-community>=0.0.10
    - langchain-core>=0.1.0
    - langchain-experimental>=0.0.6
    - python-dotenv>=1.0.0
    - streamlit>=1.29.0
    - transformers>=4.36.0
    - accelerate>=0.25.0
    - openai>=1.3.0
    - duckduckgo-search>=4.1.1
    - wikipedia>=1.4.0
    - google-search-results>=2.4.2
    - langchain-openai>=0.0.2
    - beautifulsoup4>=4.12.2
    - requests>=2.31.0
    - arxiv>=2.0.0
    - pytesseract>=0.3.10
    - yfinance>=0.2.33
    - tabulate>=0.9.0
    - playwright>=1.40.0
    - python-weather>=1.0.1
